//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESPBackend.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestData
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string TestString { get; set; }

        public override string ToString()
        {
            return $"{nameof(Id)}: {Id}, {nameof(TestString)}: {TestString}, {nameof(UserId)}: {UserId}";
        }

        public override bool Equals(object obj)
        {
            if (obj is TestData)
            {
                var to = obj as TestData;
                if (to.Id == Id && to.TestString == TestString && to.UserId == UserId)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }

            return base.Equals(obj);
        }
    }
}
